# **Temel Fonksiyon Yazımı**

In [1]:
#R’da fonksiyonlar temelde üç temel bileşenden oluşur: başlık, argüman ve gövde. Örnek olarak F_a isimli bir fonksiyon oluşturalım.
#Bu fonksiyon, kendisine verilen bir değerden 1 sayısını çıkarsın.

F_a <- function(x) {
  x - 1
  }
girdiler <- c(10, 15, 20)
ciktilar <- F_a(girdiler)
ciktilar


[1]  9 14 19

In [5]:
#Bir üs alma fonksiyonu yazalım. Bu fonksiyon, kendisine verilen bir değerin üssünü alsın.

kupFonk <- function(a) {
  sonuc <- data.frame(Hacim = a^3, TabanAlani = a^2, AlanlarToplami = 6*a^2)
  print(sonuc)
  }
kupFonk(4)

  Hacim TabanAlani AlanlarToplami
1    64         16             96


In [ ]:
# Birden fazla küp için değerlerin elde edilmesi
kupFonk2 <- function(a) {
  sonuc <- data.frame(Kenar = a, Hacim = a^3, TabanAlani = a^2, AlanlarToplami = 6*a^2)
  print(sonuc)
  }
kupFonk2(c(1, 2, 3, 4, 5))

**apply() Ailesi**

R’da istatistiksel analizler yapılırken matrislerin, listelerin veya veri setlerinin her bir satırına ya da sütununa işlemler uygulanmak istenebilir. Bu durumda döngülerin kullanılması her zaman pratik olmayabilir. apply() ailesine ait fonksiyonlarla da satırlara ve sütunlara işlemler uygulanabilir. Bu ailede apply(), lapply(), sapply(), vapply(), mapply(), rapply() ve tapply() fonksiyonları yer almaktadır. Bunlar arasından sık kullanılan dört tanesini inceleyelim.

In [7]:
matris_a <- matrix(c(1:25), nrow = 5, ncol = 5)
matris_a

[,1] [,2] [,3] [,4] [,5]
[1,] 1     6   11   16   21  
[2,] 2     7   12   17   22  
[3,] 3     8   13   18   23  
[4,] 4     9   14   19   24  
[5,] 5    10   15   20   25

In [8]:
#Satırlarla işlem yapmak için 1 sütunlarla işlem yapmak için 2 seçilir. matrisin sütunlarının max değerlerini bulmak için

apply(matris_a, 1, max)

[1] 21 22 23 24 25

In [10]:
#Sütunların ortalamasını bulmak için
apply(matris_a, 2, mean)

[1]  3  8 13 18 23

In [12]:
#Sütun Toplamları
apply(matris_a, 2, sum)

[1]  15  40  65  90 115

In [13]:
# Her bir elemanın karekokunu almak için
apply(matris_a, 2, sqrt)

[,1]     [,2]     [,3]     [,4]     [,5]    
[1,] 1.000000 2.449490 3.316625 4.000000 4.582576
[2,] 1.414214 2.645751 3.464102 4.123106 4.690416
[3,] 1.732051 2.828427 3.605551 4.242641 4.795832
[4,] 2.000000 3.000000 3.741657 4.358899 4.898979
[5,] 2.236068 3.162278 3.872983 4.472136 5.000000

In [15]:
#Her bir değeri kendisinin karesinden çıkarak yeri bir matris oluşturmak için

apply(matris_a,1,function (x){x^2-x})

[,1] [,2] [,3] [,4] [,5]
[1,]   0    2    6   12   20 
[2,]  30   42   56   72   90 
[3,] 110  132  156  182  210 
[4,] 240  272  306  342  380 
[5,] 420  462  506  552  600

**lapply() Fonksiyonu**

lapply() fonksiyonu apply() fonksiyonunun listeler, vektörler ve veri setleri için özelleştirilmiş halidir.

In [16]:
#listedeki her elemanın karekökünü alıp yeni bir liste oluşturmak için
aa <- c(1, 4, 9)
bb <- c(16, 25, 36)
liste_sayilar <- list(aa, bb)
lapply(liste_sayilar, sqrt)

[[1]]
[1] 1 2 3

[[2]]
[1] 4 5 6

In [17]:
#ortalamalarının karesini almak için
lapply(liste_sayilar, function(x) {mean(x)^2})

[[1]]
[1] 21.77778

[[2]]
[1] 658.7778

In [20]:
#vektörlerden liste oluşturuyoruz.
karakter=c("a","b","c","d","e")
sayi =c(1,2,5,4,8,6,7)
kosul=c(T,F)

liste_ol = list(karakter,sayi,kosul)
class(liste_ol)

[1] "list"

In [21]:
#liste elemanlarının sayılarını öğrenmek için
lapply(liste_ol,length)

[[1]]
[1] 5

[[2]]
[1] 7

[[3]]
[1] 2

In [22]:
#liste elemanlarını yazdırmak için
lapply(liste_ol,function(i){print(i)})

[1] "a" "b" "c" "d" "e"
[1] 1 2 5 4 8 6 7
[1]  TRUE FALSE


[[1]]
[1] "a" "b" "c" "d" "e"

[[2]]
[1] 1 2 5 4 8 6 7

[[3]]
[1]  TRUE FALSE

In [23]:
#liste elemanlarının sınıfını öğrenmek için

lapply(liste_ol,class)

[[1]]
[1] "character"

[[2]]
[1] "numeric"

[[3]]
[1] "logical"

**sapply() Fonksiyonu**

sapply() fonksiyonu ile de lapply() fonksiyonunda olduğu gibi liste, veri setleri ve vektörler üzerinde çalışılır. sapply() fonksiyonunun temel amacı çıktıları basitleştirmektir. lapply() ile elde edilen çıktılar liste biçiminde iken, sapply() ile elde edilen çıktılar daha çok vektör ya da vektörlerin özel halleri türündedir. Sonuçları daha kullanılır şekilde matris veya vektör olraka döndürür.

In [24]:
aa <- c(1, 4, 9)
bb <- c(16, 25, 36)
liste_sayilar <- list(aa, bb)

sapp <- sapply(liste_sayilar, sqrt)
sapp

[,1] [,2]
[1,] 1    4   
[2,] 2    5   
[3,] 3    6

In [26]:
#Sütun ve satır toplamlarını öğrenmek için
colSums(sapp)
rowSums(sapp)

[1]  6 15

[1] 5 7 9

In [29]:
#yeni bir liste oluşturuyoruz
sayi_liste=list(a=1:15,b=rnorm(15),c=rnorm(20))


$a
 [1]  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15

$b
 [1] -0.2173314  0.5561618  3.0214137  0.4033297  0.8204573 -0.6689889
 [7] -1.0800781 -0.4243030  0.4666731 -0.2245443 -0.7824250  0.5412416
[13]  1.6024441 -1.1686983  0.7361650

$c
 [1]  1.21870960  1.38588979 -0.75960936 -0.57625927 -0.06747235 -1.93003796
 [7] -0.66128588 -0.86489648 -1.11016102  1.31486814  1.33473487  1.32908556
[13]  3.43319047  0.13812169  0.88107641  0.36986422 -1.11764695  0.66055762
[19]  1.38613929  1.76088376

In [30]:
#listeyi oluşturan vektörlerin ortalamalarını öğrenmek için
sapply(sayi_liste,mean)

a         b         c 
8.0000000 0.2387678 0.4062876

In [31]:
yeni_veri = data.frame(list(yas=c(15,17,18,25,30),cinsiyet=c("E","K","E","K","K"),maas=c(1000,2500,1250,1450,2000)))
yeni_veri



yas cinsiyet maas
1 15  E        1000
2 17  K        2500
3 18  E        1250
4 25  K        1450
5 30  K        2000

In [33]:
#Cinsiyete göre ayırmak için
cinsiyet_veri =split(yeni_veri,yeni_veri$cinsiyet)
cinsiyet_veri

$E
  yas cinsiyet maas
1  15        E 1000
3  18        E 1250

$K
  yas cinsiyet maas
2  17        K 2500
4  25        K 1450
5  30        K 2000

In [34]:
#özet bilgileri görmek için
str(cinsiyet_veri)

List of 2
 $ E:'data.frame':	2 obs. of  3 variables:
  ..$ yas     : num [1:2] 15 18
  ..$ cinsiyet: chr [1:2] "E" "E"
  ..$ maas    : num [1:2] 1000 1250
 $ K:'data.frame':	3 obs. of  3 variables:
  ..$ yas     : num [1:3] 17 25 30
  ..$ cinsiyet: chr [1:3] "K" "K" "K"
  ..$ maas    : num [1:3] 2500 1450 2000


**tapply() Fonksiyonu**

tapply() fonksiyonu liste ve data frame türündeki nesnelere uygulandığında sonucu vektör ya da liste şeklinde vermektedir. Eğer tapply() içinde kullanılan fonksiyon tek bir değer veriyorsa çıktı vektör olur, birden fazla değer veriyorsa çıktı liste olacaktır.

In [38]:
#örnek veri setimizde cinsiyete göre ortalama geliri bulmak için tapply fonksiyonunu kullanabiliriz.

cinsiyete_gore_gelir = tapply(yeni_veri$maas,yeni_veri$cinsiyet,mean)
cinsiyete_gore_gelir

E        K 
1125.000 1983.333

In [41]:
#Cinsiyete göre yaş ortalamasına bakmak içi
cinsiyet_yas = tapply(yeni_veri$yas,yeni_veri$cinsiyet,mean)
cinsiyet_yas

E    K 
16.5 24.0

In [42]:
ad <- c("oguz","sabahattin","yusuf", "tezer")
cinsiyet <- c("E", "E", "E", "K")
boy <- c(185, 170, 175, 165)
cinsiyet <- factor(cinsiyet)
yeniliste <- list(ad = ad, cinsiyet = cinsiyet, boy = boy)
# cinsiyete göre boy uzunluklarını küçükten büyüğe sıralanması (cinsiyet faktör idi)
tapply(yeniliste$boy, yeniliste$cinsiyet, sort)

$E
[1] 170 175 185

$K
[1] 165

In [43]:
# adlara göre boy uzunluklarını küçükten büyüğe sıralanması
tapply(yeniliste$boy, yeniliste$ad, sort)

oguz sabahattin      tezer      yusuf 
       185        170        165        175