# **Temel Fonksiyon Yazımı**

In [1]:
#R’da fonksiyonlar temelde üç temel bileşenden oluşur: başlık, argüman ve gövde. Örnek olarak F_a isimli bir fonksiyon oluşturalım.
#Bu fonksiyon, kendisine verilen bir değerden 1 sayısını çıkarsın.

F_a <- function(x) {
  x - 1
  }
girdiler <- c(10, 15, 20)
ciktilar <- F_a(girdiler)
ciktilar


[1]  9 14 19

In [50]:
#Ortalama fonksiyonumuzu kendimiz yazalaım fonksiyon oluşturup vektördeki değerlerimizin ortalamasını aldırdık

ortalama_al = function(x) {
  sum(x)/length(x)
}
a=5:15
b=c(2,5,3,6,8,7,5,4,12)
ortalama_al(a)
ortalama_al(b)

[1] 10

[1] 5.777778

In [54]:
#1 dne istediğimiz sayıya kadar merhaba yazdıran fonksiyon yazalım

yazdir = function(sayi){
  for(i in 1:sayi){
    print("Merhaba")
  }
}
yazdir(5)

[1] "Merhaba"
[1] "Merhaba"
[1] "Merhaba"
[1] "Merhaba"
[1] "Merhaba"


In [5]:
#Bir üs alma fonksiyonu yazalım. Bu fonksiyon, kendisine verilen bir değerin üssünü alsın.

kupFonk <- function(a) {
  sonuc <- data.frame(Hacim = a^3, TabanAlani = a^2, AlanlarToplami = 6*a^2)
  print(sonuc)
  }
kupFonk(4)

  Hacim TabanAlani AlanlarToplami
1    64         16             96


In [ ]:
# Birden fazla küp için değerlerin elde edilmesi
kupFonk2 <- function(a) {
  sonuc <- data.frame(Kenar = a, Hacim = a^3, TabanAlani = a^2, AlanlarToplami = 6*a^2)
  print(sonuc)
  }
kupFonk2(c(1, 2, 3, 4, 5))

**apply() Ailesi**

R’da istatistiksel analizler yapılırken matrislerin, listelerin veya veri setlerinin her bir satırına ya da sütununa işlemler uygulanmak istenebilir. Bu durumda döngülerin kullanılması her zaman pratik olmayabilir. apply() ailesine ait fonksiyonlarla da satırlara ve sütunlara işlemler uygulanabilir. Bu ailede apply(), lapply(), sapply(), vapply(), mapply(), rapply() ve tapply() fonksiyonları yer almaktadır. Bunlar arasından sık kullanılan dört tanesini inceleyelim.

In [7]:
matris_a <- matrix(c(1:25), nrow = 5, ncol = 5)
matris_a

[,1] [,2] [,3] [,4] [,5]
[1,] 1     6   11   16   21  
[2,] 2     7   12   17   22  
[3,] 3     8   13   18   23  
[4,] 4     9   14   19   24  
[5,] 5    10   15   20   25

In [8]:
#Satırlarla işlem yapmak için 1 sütunlarla işlem yapmak için 2 seçilir. matrisin sütunlarının max değerlerini bulmak için

apply(matris_a, 1, max)

[1] 21 22 23 24 25

In [10]:
#Sütunların ortalamasını bulmak için
apply(matris_a, 2, mean)

[1]  3  8 13 18 23

In [12]:
#Sütun Toplamları
apply(matris_a, 2, sum)

[1]  15  40  65  90 115

In [13]:
# Her bir elemanın karekokunu almak için
apply(matris_a, 2, sqrt)

[,1]     [,2]     [,3]     [,4]     [,5]    
[1,] 1.000000 2.449490 3.316625 4.000000 4.582576
[2,] 1.414214 2.645751 3.464102 4.123106 4.690416
[3,] 1.732051 2.828427 3.605551 4.242641 4.795832
[4,] 2.000000 3.000000 3.741657 4.358899 4.898979
[5,] 2.236068 3.162278 3.872983 4.472136 5.000000

In [15]:
#Her bir değeri kendisinin karesinden çıkarak yeri bir matris oluşturmak için

apply(matris_a,1,function (x){x^2-x})

[,1] [,2] [,3] [,4] [,5]
[1,]   0    2    6   12   20 
[2,]  30   42   56   72   90 
[3,] 110  132  156  182  210 
[4,] 240  272  306  342  380 
[5,] 420  462  506  552  600

**lapply() Fonksiyonu**

lapply() fonksiyonu apply() fonksiyonunun listeler, vektörler ve veri setleri için özelleştirilmiş halidir.

In [16]:
#listedeki her elemanın karekökünü alıp yeni bir liste oluşturmak için
aa <- c(1, 4, 9)
bb <- c(16, 25, 36)
liste_sayilar <- list(aa, bb)
lapply(liste_sayilar, sqrt)

[[1]]
[1] 1 2 3

[[2]]
[1] 4 5 6

In [17]:
#ortalamalarının karesini almak için
lapply(liste_sayilar, function(x) {mean(x)^2})

[[1]]
[1] 21.77778

[[2]]
[1] 658.7778

In [20]:
#vektörlerden liste oluşturuyoruz.
karakter=c("a","b","c","d","e")
sayi =c(1,2,5,4,8,6,7)
kosul=c(T,F)

liste_ol = list(karakter,sayi,kosul)
class(liste_ol)

[1] "list"

In [21]:
#liste elemanlarının sayılarını öğrenmek için
lapply(liste_ol,length)

[[1]]
[1] 5

[[2]]
[1] 7

[[3]]
[1] 2

In [22]:
#liste elemanlarını yazdırmak için
lapply(liste_ol,function(i){print(i)})

[1] "a" "b" "c" "d" "e"
[1] 1 2 5 4 8 6 7
[1]  TRUE FALSE


[[1]]
[1] "a" "b" "c" "d" "e"

[[2]]
[1] 1 2 5 4 8 6 7

[[3]]
[1]  TRUE FALSE

In [23]:
#liste elemanlarının sınıfını öğrenmek için

lapply(liste_ol,class)

[[1]]
[1] "character"

[[2]]
[1] "numeric"

[[3]]
[1] "logical"

**sapply() Fonksiyonu**

sapply() fonksiyonu ile de lapply() fonksiyonunda olduğu gibi liste, veri setleri ve vektörler üzerinde çalışılır. sapply() fonksiyonunun temel amacı çıktıları basitleştirmektir. lapply() ile elde edilen çıktılar liste biçiminde iken, sapply() ile elde edilen çıktılar daha çok vektör ya da vektörlerin özel halleri türündedir. Sonuçları daha kullanılır şekilde matris veya vektör olraka döndürür.

In [24]:
aa <- c(1, 4, 9)
bb <- c(16, 25, 36)
liste_sayilar <- list(aa, bb)

sapp <- sapply(liste_sayilar, sqrt)
sapp

[,1] [,2]
[1,] 1    4   
[2,] 2    5   
[3,] 3    6

In [26]:
#Sütun ve satır toplamlarını öğrenmek için
colSums(sapp)
rowSums(sapp)

[1]  6 15

[1] 5 7 9

In [29]:
#yeni bir liste oluşturuyoruz
sayi_liste=list(a=1:15,b=rnorm(15),c=rnorm(20))


$a
 [1]  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15

$b
 [1] -0.2173314  0.5561618  3.0214137  0.4033297  0.8204573 -0.6689889
 [7] -1.0800781 -0.4243030  0.4666731 -0.2245443 -0.7824250  0.5412416
[13]  1.6024441 -1.1686983  0.7361650

$c
 [1]  1.21870960  1.38588979 -0.75960936 -0.57625927 -0.06747235 -1.93003796
 [7] -0.66128588 -0.86489648 -1.11016102  1.31486814  1.33473487  1.32908556
[13]  3.43319047  0.13812169  0.88107641  0.36986422 -1.11764695  0.66055762
[19]  1.38613929  1.76088376

In [30]:
#listeyi oluşturan vektörlerin ortalamalarını öğrenmek için
sapply(sayi_liste,mean)

a         b         c 
8.0000000 0.2387678 0.4062876

In [31]:
yeni_veri = data.frame(list(yas=c(15,17,18,25,30),cinsiyet=c("E","K","E","K","K"),maas=c(1000,2500,1250,1450,2000)))
yeni_veri



yas cinsiyet maas
1 15  E        1000
2 17  K        2500
3 18  E        1250
4 25  K        1450
5 30  K        2000

In [33]:
#Cinsiyete göre ayırmak için
cinsiyet_veri =split(yeni_veri,yeni_veri$cinsiyet)
cinsiyet_veri

$E
  yas cinsiyet maas
1  15        E 1000
3  18        E 1250

$K
  yas cinsiyet maas
2  17        K 2500
4  25        K 1450
5  30        K 2000

In [34]:
#özet bilgileri görmek için
str(cinsiyet_veri)

List of 2
 $ E:'data.frame':	2 obs. of  3 variables:
  ..$ yas     : num [1:2] 15 18
  ..$ cinsiyet: chr [1:2] "E" "E"
  ..$ maas    : num [1:2] 1000 1250
 $ K:'data.frame':	3 obs. of  3 variables:
  ..$ yas     : num [1:3] 17 25 30
  ..$ cinsiyet: chr [1:3] "K" "K" "K"
  ..$ maas    : num [1:3] 2500 1450 2000


**tapply() Fonksiyonu**

tapply() fonksiyonu liste ve data frame türündeki nesnelere uygulandığında sonucu vektör ya da liste şeklinde vermektedir. Eğer tapply() içinde kullanılan fonksiyon tek bir değer veriyorsa çıktı vektör olur, birden fazla değer veriyorsa çıktı liste olacaktır.

In [38]:
#örnek veri setimizde cinsiyete göre ortalama geliri bulmak için tapply fonksiyonunu kullanabiliriz.

cinsiyete_gore_gelir = tapply(yeni_veri$maas,yeni_veri$cinsiyet,mean)
cinsiyete_gore_gelir

E        K 
1125.000 1983.333

In [41]:
#Cinsiyete göre yaş ortalamasına bakmak içi
cinsiyet_yas = tapply(yeni_veri$yas,yeni_veri$cinsiyet,mean)
cinsiyet_yas

E    K 
16.5 24.0

In [42]:
ad <- c("oguz","sabahattin","yusuf", "tezer")
cinsiyet <- c("E", "E", "E", "K")
boy <- c(185, 170, 175, 165)
cinsiyet <- factor(cinsiyet)
yeniliste <- list(ad = ad, cinsiyet = cinsiyet, boy = boy)
# cinsiyete göre boy uzunluklarını küçükten büyüğe sıralanması (cinsiyet faktör idi)
tapply(yeniliste$boy, yeniliste$cinsiyet, sort)

$E
[1] 170 175 185

$K
[1] 165

In [43]:
# adlara göre boy uzunluklarını küçükten büyüğe sıralanması
tapply(yeniliste$boy, yeniliste$ad, sort)

oguz sabahattin      tezer      yusuf 
       185        170        165        175

# **Bazı Yararlı Fonksiyonlar**

R’da herhangi bir paket (package) indirmeden kullanılabilen, çok sayıda fonksiyon bulunmaktadır. Bu fonksiyonların bir kısmı, kitabın önceki bölümlerinde ele alındı. Bunun haricinde, çeşitli amaçlarla kullanılabilecek birkaç fonksiyonu burada listelemek istedim.

##**dput() Fonksiyonu**

dput() fonksiyonu ile çalışma alanınızda kayıtlı bir veri setini satır komutları haline getirebilirsiniz. Bu özellikle, veri setinizi ya da veri setinizin bir kısmını R’da çalışacak olan biriyle paylaşmak istediğinizde yararlı olabilir.

In [56]:
data(iris)
iris_ornek <- head(iris, 5)
iris_ornek

Sepal.Length Sepal.Width Petal.Length Petal.Width Species
1 5.1          3.5         1.4          0.2         setosa 
2 4.9          3.0         1.4          0.2         setosa 
3 4.7          3.2         1.3          0.2         setosa 
4 4.6          3.1         1.5          0.2         setosa 
5 5.0          3.6         1.4          0.2         setosa

In [57]:
dput(iris_ornek)

structure(list(Sepal.Length = c(5.1, 4.9, 4.7, 4.6, 5), Sepal.Width = c(3.5, 
3, 3.2, 3.1, 3.6), Petal.Length = c(1.4, 1.4, 1.3, 1.5, 1.4), 
    Petal.Width = c(0.2, 0.2, 0.2, 0.2, 0.2), Species = structure(c(1L, 
    1L, 1L, 1L, 1L), levels = c("setosa", "versicolor", "virginica"
    ), class = "factor")), row.names = c(NA, 5L), class = "data.frame")


dput(iris_ornek) yukarıda structure() fonksiyonu içinde verilen fonksiyon, argüman ve diğer bilgileri verecektir. Bunu kopyalayarak başka biri ile paylaşabilirsiniz. Böylelikle, o kişi de sizin verdiğiniz veriyi R’a aktarabilir.

In [ ]:
#ls() fonksiyonunu kullanarak çalışma alanınıza kayıtlı tüm nesneleri listeleyebilirsiniz.

In [ ]:
#rm() fonksiyonunu kullanarak çalışma alanınızda kayıtlı olan bir nesneyi silebilirsiniz.
#rm(list = ls()) komutunu çalıştırarak çalışma alanınızda kayıtlı olan tüm nesneleri silebilirsiniz.

In [ ]:
#identical() fonksiyonu kendisine verdiğiniz nesnelerin birebir aynı olup olmadığını test etmede kullanılır. Bu kitapta da kullanılmıştır.
#Örneğin, iki vektörün aynı olup olmadığını aşağıdaki kodlar ile test edelim

In [ ]:
vektor_1 <- 1:5
vektor_2 <- seq(5)
identical(vektor_1, vektor_2)

In [ ]:
matris_1 <- diag(1, 3, 3)
matris_2 <- matrix(c(1, 0, 0, 0, 1, 0, 0, 0, 1), 3, 3)
identical(matris_1, matris_2)

In [58]:
#Sys.Date() ve Sys.time() fonksiyonları sistemin tarih ve saatini yazdırmaya yarar. Çıktısı ‘tarih’ türünde bir nesnedir.
Sys.Date()
Sys.time()

[1] "2025-12-29"

[1] "2025-12-29 11:54:52 UTC"

In [59]:
#aggregate() fonksiyonu veriyi alt veri setlerine göre gruplandırarak işlem yapma olanağı sağlar.
#Örnek için R’da bulunan airquality veri setini ele alalım. Bu veri setindeki Ozone ve
#Temp değişkenlerinin aylara (Month) göre ortalamalarını bulmak için aşağıdaki satır komutları kullanılır.

head(airquality)

Ozone Solar.R Wind Temp Month Day
1 41    190      7.4 67   5     1  
2 36    118      8.0 72   5     2  
3 12    149     12.6 74   5     3  
4 18    313     11.5 62   5     4  
5 NA     NA     14.3 56   5     5  
6 28     NA     14.9 66   5     6

In [60]:
aggregate(cbind(Ozone, Temp) ~ Month, data = airquality, mean)

Month Ozone    Temp    
1 5     23.61538 66.73077
2 6     29.44444 78.22222
3 7     59.11538 83.88462
4 8     59.96154 83.96154
5 9     31.44828 76.89655

In [62]:
#cor() fonksiyonu ile korelasyon matrisleri (tabloları) elde edilebilir.
#Örneğin R’da bulunan mtcars isimli veri setindeki mpg, cyl ve disp değişkenlerinin ikili korelasyonlarını hesaplayalım.

cor(mtcars[, 1:3])

#Yukarıdaki satır komutunda köşeli parantez içinde verilen 1:3 ifadesi birinci sütundan üçüncü sütuna kadar olan sütunları
#seçmek için kullanılmaktadır. Bu nedenle çıktıda bu sütunlar (mpg, cyl ve disp) yer almaktadır.

mpg        cyl        disp      
mpg   1.0000000 -0.8521620 -0.8475514
cyl  -0.8521620  1.0000000  0.9020329
disp -0.8475514  0.9020329  1.0000000

In [63]:
#merge() fonksiyonu yardımıyla iki veri seti bir değişken üzerinden birleştirilebilir. Aşağıdaki örnekte
#Basketbol Süper Ligi ile ilgili istatistiklerden oluşan iki ayrı data frame üretilmiştir.

# örnek uygulama için veri setlerini oluşturalım
BSL1 <- data.frame(id = 1:11,
                   takim = c("Anadolu Efes", "Fenerbahçe", "Eczacıbaşı", "Galatasaray", "İTÜ", "Ülkerspor",
                             "Beşiktaş", "Tofaş", "Pınar Karşıyaka", "Altınordu", "Muhafızgücü"),
                   sampiyonluk = c(16, 10, 8, 5, 5, 4, 2, 2, 2, 1, 1))
BSL2 <- data.frame(ID = c(11, 10, 9, 8, 7, 6, 5, 4, 3, 2, 1),
                   ikincilik = c(0, 0, 2, 3, 7, 5, 1, 4, 1, 10, 13),
                   son_sapiyonluk = c("1974", "1967", "2015", "2000", "2012", "2006",
                                      "1973", "2013", "1989", "2022", "2023"))

# veri setlerini inceleyelim
BSL1

id takim           sampiyonluk
1   1 Anadolu Efes    16         
2   2 Fenerbahçe      10         
3   3 Eczacıbaşı       8         
4   4 Galatasaray      5         
5   5 İTÜ              5         
6   6 Ülkerspor        4         
7   7 Beşiktaş         2         
8   8 Tofaş            2         
9   9 Pınar Karşıyaka  2         
10 10 Altınordu        1         
11 11 Muhafızgücü      1

In [64]:
BSL2

ID ikincilik son_sapiyonluk
1  11  0        1974          
2  10  0        1967          
3   9  2        2015          
4   8  3        2000          
5   7  7        2012          
6   6  5        2006          
7   5  1        1973          
8   4  4        2013          
9   3  1        1989          
10  2 10        2022          
11  1 13        2023

In [ ]:
#Görüldüğü üzere BSL1 ve BSL2 veri setlerinde id ve ID değişkenleri aynıdır. Bu iki veri setindeki bilgiler bu
#değişkenler üzerinden birleştirilebilir.

In [65]:
merge(BSL1, BSL2, by.x = "id", by.y = "ID")

id takim           sampiyonluk ikincilik son_sapiyonluk
1   1 Anadolu Efes    16          13        2023          
2   2 Fenerbahçe      10          10        2022          
3   3 Eczacıbaşı       8           1        1989          
4   4 Galatasaray      5           4        2013          
5   5 İTÜ              5           1        1973          
6   6 Ülkerspor        4           5        2006          
7   7 Beşiktaş         2           7        2012          
8   8 Tofaş            2           3        2000          
9   9 Pınar Karşıyaka  2           2        2015          
10 10 Altınordu        1           0        1967          
11 11 Muhafızgücü      1           0        1974

sub(), gsub() ve substr() fonksiyonları ile bir karakter vektöründeki ifade bulunabilir ve bu ifade istenen karakterler ile değiştirilebilir.

In [ ]:
# ilk e harfini * ile değiştirme
sub("e", "*", "metehan")

In [ ]:
# tüm e harflerini * ile değiştirme
gsub("e", "*", "metehan")

In [ ]:
# kelimenin 1, 2, 3, ve 4. karakterini seçme
substr("metehan", 1, 4)

In [ ]:
#grep() ve grepl() fonksiyonları ile bir nesne içindeki bazı spesifik karakterler bulunabilir.
#Örneğin, BAFTA ödülüne layık görülen filmlerin isimlerini ve türlerini inceleyelim.

In [66]:
# örneklendirmek için bir veri seti içe aktaralım.
BAFTA_film <- read.csv("https://raw.githubusercontent.com/gungorMetehan/BAFTA/main/BAFTA_film.csv")

# grep() yardımıyla filmler arasında adında 'la' ifadesi geçen filmlerin indekslerini bulalım.
grep("la", BAFTA_film$film)

[1]  1  5 12 25 35 64

In [67]:
# grepl() yardımıyla film türleri arasında 'Drama' türünde olan filmleri bulmaya çalışalım.
grepl("Drama", BAFTA_film$genres)

[1]  TRUE  TRUE  TRUE  TRUE  TRUE  TRUE  TRUE  TRUE  TRUE  TRUE  TRUE  TRUE
[13]  TRUE  TRUE  TRUE  TRUE  TRUE  TRUE  TRUE  TRUE  TRUE  TRUE  TRUE  TRUE
[25]  TRUE  TRUE  TRUE  TRUE  TRUE  TRUE  TRUE  TRUE  TRUE  TRUE  TRUE  TRUE
[37]  TRUE  TRUE  TRUE FALSE  TRUE  TRUE  TRUE  TRUE  TRUE  TRUE  TRUE FALSE
[49]  TRUE  TRUE  TRUE  TRUE  TRUE  TRUE  TRUE  TRUE  TRUE  TRUE  TRUE  TRUE
[61] FALSE FALSE  TRUE  TRUE  TRUE  TRUE  TRUE  TRUE  TRUE  TRUE  TRUE  TRUE
[73]  TRUE  TRUE  TRUE  TRUE  TRUE

grep() ve grepl() fonksiyonları benzer amaçlarla kullanılsa da, çıktılarının farklı olduğu görülecektir. grep() çıktı olarak ilgili satırların indekslerini verirken, grepl() her satırda aranan değerin bulunup bulunmadığına ilişkin mantıksal değerleri (TRUE ya da FALSE) verir.

In [69]:
# beş tane gerçek (reel) sayıdan oluşan bir vektör oluşturalım
bes_gercek_sayi <- c(.5, 8, 3.99, 1.04, 9.86)

# round() ile yuvarlama yapılmaktadır. digits argümanına girilen değer virgülden sonra kaç tane basamak olmasını istediğimizi gösterir.
round(bes_gercek_sayi, digits = 1)

[1] 0.5 8.0 4.0 1.0 9.9

In [70]:
# signif() fonksiyonu sayıları önemli görülen toplam basamak sayısı kadar yuvarlama yapar.
signif(bes_gercek_sayi, digits = 2)

[1] 0.5 8.0 4.0 1.0 9.9

In [71]:
# ceiling() fonksiyonu vektördeki sayıları kendisine ya da üstündeki ilk tam sayıya yuvarlar.
ceiling(bes_gercek_sayi)

[1]  1  8  4  2 10

In [ ]:
# floor() fonksiyonu vektördeki sayıları kendisine ya da altındaki ilk tam sayıya yuvarlar.
floor(bes_gercek_sayi)

In [72]:
# trunc() fonksiyonu vektördeki sayıların ondalık kısımlarını siler.
trunc(bes_gercek_sayi)

[1] 0 8 3 1 9