# **DİZİLER**
Diziler, vektörlerin ve matrislerin genelleştirilmiş halidir. Vektörler tek, matrisler ise iki boyutlu dizilerdir. Diziler, tek tür veri içerebilir.İkiden fazla boyutu olan dizi oluşturmak için array() fonksiyonundan yararlanılır.


---




### Boş bir dizinin oluşturulması




array(data = NA, dim = length(data), dimnames = NULL)

In [3]:
#1 den 24 e kadar 2 satır,3 sütundan oluşan 4 matris oluşturmak için; sonuç doğru gösterilmiyor. 4 tablo gibi düşünebiliriz.
x <- array(1:24, dim = c(2, 3, 4))
x

, , 1

     [,1] [,2] [,3]
[1,]    1    3    5
[2,]    2    4    6

, , 2

     [,1] [,2] [,3]
[1,]    7    9   11
[2,]    8   10   12

, , 3

     [,1] [,2] [,3]
[1,]   13   15   17
[2,]   14   16   18

, , 4

     [,1] [,2] [,3]
[1,]   19   21   23
[2,]   20   22   24

In [4]:
#4 matristen 3. matrisle çalışmak için, diğer matrislerde bu şekilde oluşur.

x[,,3]

[,1] [,2] [,3]
[1,] 13   15   17  
[2,] 14   16   18

In [9]:
vektor_a <- c(5, 9, 3)
vektor_b <- c(10, 11, 12, 13, 14, 15)
sonuc <- array(c(vektor_a, vektor_b), dim = c(3, 3, 2))
sonuc[,,1]
print("----------")
sonuc[2,,2]#2. matrisin sadece 2. satırını getirmek için

[,1] [,2] [,3]
[1,] 5    10   13  
[2,] 9    11   14  
[3,] 3    12   15

[1] "----------"


[1]  9 11 14