# **Matrisler**
Matrisler, vektörler gibi tek bir tür veri içerir. Buna karşın, vektörler tek boyutlu iken matrisler iki boyutlu veri yapılarıdır. Matris oluşturmanın birden fazla yolu vardır. Eşit uzunluktaki vektörler birleştirilerek matris oluşturulabilir. Sütunların birleştirilmesi için cbind(), satırların birleştirilmesi için rbind() fonksiyonları kullanılır.

In [ ]:
#Birden fazla vektör kullanarak matris oluşturmak için
# öğrencilerin boyları için bir vektör, kiloları için başka bir vektör oluşturma
ogrenci_boy <- c(162, 168, 175, 182, 140)
ogrenci_kilo <- c(48, 50, 52, 55, 48)

mm_1 <- cbind(ogrenci_boy, ogrenci_kilo)
mm_1

ogrenci_boy ogrenci_kilo
[1,] 162         48          
[2,] 168         50          
[3,] 175         52          
[4,] 182         55          
[5,] 140         48

In [ ]:
mm_2 <- rbind(ogrenci_boy, ogrenci_kilo)
mm_2

[,1] [,2] [,3] [,4] [,5]
ogrenci_boy  162  168  175  182  140 
ogrenci_kilo  48   50   52   55   48

In [ ]:
class(mm_1) ; class(mm_2)

[1] "matrix" "array"

[1] "matrix" "array"

In [ ]:
#Tek vektörden istenilen sütün ve satır kadar matris üretmek için 2 sütun 4 satırlık matris
a <-  matrix(c(2,3,5,8,9,45,25,13),nrow=4,ncol=2)
a

[,1] [,2]
[1,] 2     9  
[2,] 3    45  
[3,] 5    25  
[4,] 8    13

In [ ]:
#Matrisin kaç satır kaç sütundan oluştuğunu öğrenmek için dim() fonksiyonu kullanılır.
dim(a)

[1] 4 2

In [ ]:
#matris sıralanmasını yukardan aşağıya değilse soldan sağa göre yapmak için byrow=TRUE ayarını ekliyorum varsayılan FALSE dir.
# İlk başta ilk sütun oluşur sonra sırası ile sütunları oluşturarak gider. Varsayılan satırları oluşturarak gider.
yeni_matris <- matrix(1:20, nrow = 4, ncol = 5, byrow = T)

In [ ]:
#oluşturulan matrise başlıklar atamak için
rownames(yeni_matris) <- c("Satir1","Satir2","Satir3","Satir4")
colnames(yeni_matris) <- c("sutun1","sutun2","sutun3","sutun4","sutun5")

yeni_matris

sutun1 sutun2 sutun3 sutun4 sutun5
Satir1  1      2      3      4      5    
Satir2  6      7      8      9     10    
Satir3 11     12     13     14     15    
Satir4 16     17     18     19     20

In [ ]:
# sütun ve satırlara isim verme (paste() fonksiyonundan yararlanarak)
colnames(yeni_matris) <- paste("A", c(1:5), sep = "")
yeni_matris

A1 A2 A3 A4 A5
Satir1  1  2  3  4  5
Satir2  6  7  8  9 10
Satir3 11 12 13 14 15
Satir4 16 17 18 19 20

In [ ]:
rownames(yeni_matris) <- paste("", c(1:4), sep = "")
yeni_matris

A1 A2 A3 A4 A5
1  1  2  3  4  5
2  6  7  8  9 10
3 11 12 13 14 15
4 16 17 18 19 20

In [ ]:
#Matrisin istenilen elemanına erişmek için 2. satır 3. sütun da bulunan değer nedir?
yeni_matris[2,3]

[1] 8

In [ ]:
# sadece istenilen satır veye sütundaki tüm değerleri görmek için
yeni_matris[2,]
yeni_matris[,5]
yeni_matris[c(1,4),-1]
yeni_matris[-1, ] #1. satır harici diğerlerini getirir.
matris7[-c(3), ]#3. satır harici diğerlerini getirir.

sutun1 sutun2 sutun3 sutun4 sutun5 
     6      7      8      9     10

Satir1 Satir2 Satir3 Satir4 
     5     10     15     20

sutun2 sutun3 sutun4 sutun5
Satir1  2      3      4      5    
Satir4 17     18     19     20

In [ ]:
d_matris <- matrix(1:4,nrow = 2,ncol = 2,byrow = TRUE)
d_matris

[,1] [,2]
[1,] 1    2   
[2,] 3    4

In [ ]:
#Transpose işlemi yani satırları sütunlara dönüştürmek için t()fonksiyonu kullanılır.
t(d_matris)

[,1] [,2]
[1,] 1    3   
[2,] 2    4

In [ ]:
#Matrislerde aritmetik işlemler yapılabilir. 5* matris ile matrisin tüm değerleri 5 ile çarpılır.

bes_matris<-5*d_matris
bes_matris


[,1] [,2]
[1,]  5   10  
[2,] 15   20

In [ ]:
#Eşit sütun ve satır sayısına sahip matrislerde de aritmetik işlemler yapılabilir.
3*d_matris+d_matris

[,1] [,2]
[1,]  4    8  
[2,] 12   16

In [ ]:
# matris ile devriğinin çarpılması
d_matris %*% t(d_matris)

[,1] [,2]
[1,]  5   11  
[2,] 11   25

In [ ]:
#Matrislerin benzerliğini karşılaştırmak için biribirinin aynısı mı sorgusu yapar benzerse true döner değilse false
identical(d_matris,bes_matris)

[1] FALSE

In [ ]:
#iki farklı vektörün seçilen hücre değerlerini karşılaştırdık.
identical(matris8[2,3], matris9[3,2])

[1] FALSE

In [ ]:
#Matrise başka bir matristen sütun eklemek için
matris8 <- matrix(1:30,,6)
matris8

[,1] [,2] [,3] [,4] [,5] [,6]
[1,] 1     6   11   16   21   26  
[2,] 2     7   12   17   22   27  
[3,] 3     8   13   18   23   28  
[4,] 4     9   14   19   24   29  
[5,] 5    10   15   20   25   30

In [ ]:
matris9 <- cbind(matris8, 100:104)
matris9

[,1] [,2] [,3] [,4] [,5] [,6] [,7]
[1,] 1     6   11   16   21   26   100 
[2,] 2     7   12   17   22   27   101 
[3,] 3     8   13   18   23   28   102 
[4,] 4     9   14   19   24   29   103 
[5,] 5    10   15   20   25   30   104

In [ ]:
# bir matris, bir vektör ile çarpılabilir
vektorA <- 1:5
matris9*vektorA

[,1] [,2] [,3] [,4] [,5] [,6] [,7]
[1,]  1    6   11    16   21   26  100 
[2,]  4   14   24    34   44   54  202 
[3,]  9   24   39    54   69   84  306 
[4,] 16   36   56    76   96  116  412 
[5,] 25   50   75   100  125  150  520

In [ ]:
# m1 matrisinin oluşturulması
matris1 <- matrix(1:15, 3, 5)
matris1

# sütun ev satır toplamları
colSums(matris1)
rowSums(matris1)

[,1] [,2] [,3] [,4] [,5]
[1,] 1    4    7    10   13  
[2,] 2    5    8    11   14  
[3,] 3    6    9    12   15

[1]  6 15 24 33 42

[1] 35 40 45

In [ ]:
# sütun ve satır ortalamaları
colMeans(matris1)
rowMeans(matris1)

[1]  2  5  8 11 14

[1] 7 8 9

In [ ]:
#Köşegeni 1 olan matris oluşturmak için
kose_bir<- diag(5)
kose_bir

[,1] [,2] [,3] [,4] [,5]
[1,] 1    0    0    0    0   
[2,] 0    1    0    0    0   
[3,] 0    0    1    0    0   
[4,] 0    0    0    1    0   
[5,] 0    0    0    0    1